class GenerationError(Exception):
    pass


class InternalError(Exception):
    pass